"""
Runs the pipeline over a blind dataset with no ground truth and packages the result into a JPlag-viewer-compatible archive.jplag.
"""

import argparse
import datetime
import json
import shutil
import zipfile
from pathlib import Path

import numpy as np

from pipeline import run_pipeline, GST_CACHE_DIR

README_TEXT = (
    "This is a software plagiarism report generated by CDS (via generate_report.py).\n"
    "To view the report, get JPlag from https://github.com/jplag/JPlag/releases/latest, "
    "start the jar, and drag this report onto the locally hosted page.\n"
    "Match/highlight spans come from this pipeline's own GST tiling, not JPlag's tokenizer, so "
    "exact token boundaries may differ slightly from a native JPlag run on the same submissions.\n"
)


def copy_submission_files(zf: zipfile.ZipFile, submission_paths: list[str]) -> dict[str, dict[str, dict]]:
    # files: JPlag's viewer reads raw source out of files/<submission_id>/..., so copy every file under each submission's root in under that id, same relative layout JPlag itself uses
    file_index: dict[str, dict[str, dict]] = {}
    for sub_path_str in submission_paths:
        sub_id = Path(sub_path_str).name
        sub_path = Path(sub_path_str)
        sources = [sub_path] if sub_path.is_file() else sorted(p for p in sub_path.rglob("*") if p.is_file())
        file_index[sub_id] = {}
        for src in sources:
            rel_name = src.name if sub_path.is_file() else str(src.relative_to(sub_path))
            arcname = f"files/{sub_id}/{rel_name}"
            zf.write(src, arcname)
            # tokenCount: real JPlag fills this from its own tokenizer, which we don't run here, so 0 is an honest placeholder rather than a fabricated count
            file_index[sub_id][f"{sub_id}/{rel_name}"] = {"tokenCount": 0}
    return file_index


def build_distribution(fused_matrix: np.ndarray) -> dict[str, list[int]]:
    # histogram: JPlag buckets pairwise AVG/MAX similarities into 100 bins (0-1) for its distribution chart -- we only have one fused score per pair, so both bins are built from the same values
    n = fused_matrix.shape[0]
    iu, ju = np.triu_indices(n, k=1)
    scores = fused_matrix[iu, ju]
    counts, _ = np.histogram(scores, bins=100, range=(0.0, 1.0))
    return {"AVG": counts.tolist(), "MAX": counts.tolist()}


def load_gst_matches(path: Path) -> dict[tuple[str, str], list[dict]]:
    # loading: gst_matches.json is a flat list of {first, second, matches} records written by pipeline.py -- turn it back into a (first_id, second_id) -> matches lookup for build_jplag_archive
    if not path.exists():
        return {}
    with open(path) as f:
        records = json.load(f)
    return {(r["first"], r["second"]): r["matches"] for r in records}


def build_jplag_archive(output_path: str, submission_paths: list[str], fused_matrix: np.ndarray, clusters: dict[str, int], root_dirs: list[str], gst_matches: dict[tuple[str, str], list[dict]] | None = None) -> None:
    gst_matches = gst_matches or {}
    ids = [Path(p).name for p in submission_paths]
    submission_ids = dict(zip(ids, ids))
    n = len(submission_paths)
    iu, ju = np.triu_indices(n, k=1)

    # clustering: group by cluster id, dropping noise (-1) since JPlag's own cluster.json only lists members that made a cluster; averageSimilarity is real (mean fused score within the cluster), strength is left at 0.0 since that's JPlag's own clustering-quality statistic, not something we compute
    members_by_cluster: dict[int, list[str]] = {}
    for i, sub_id in enumerate(ids):
        cid = clusters[submission_paths[i]]
        if cid == -1:
            continue
        members_by_cluster.setdefault(cid, []).append(sub_id)
    cluster_list = []
    for members in members_by_cluster.values():
        member_idx = [ids.index(m) for m in members]
        pair_scores = [fused_matrix[a, b] for a in member_idx for b in member_idx if a < b]
        avg_sim = float(np.mean(pair_scores)) if pair_scores else 0.0
        cluster_list.append({"averageSimilarity": avg_sim, "strength": 0.0, "members": members})

    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.txt", README_TEXT)
        zf.writestr("submissionMappings.json", json.dumps({"submissionIds": submission_ids}))
        zf.writestr("cluster.json", json.dumps(cluster_list))
        zf.writestr("distribution.json", json.dumps(build_distribution(fused_matrix)))

        # options: a minimal but validly-shaped options.json -- real values where we have them (submission dirs), defaults elsewhere since these are JPlag's own tokenizer/clustering-algorithm settings, not something the fused-similarity pipeline configures
        options = {
            "language": "text", "minimumTokenMatch": 9, "submissionDirectories": root_dirs,
            "oldSubmissionDirectories": [], "baseCodeSubmissionDirectory": None, "subdirectoryName": None,
            "fileSuffixes": [], "exclusionFileName": None, "similarityMetric": "AVG", "similarityThreshold": 0.0,
            "maximumNumberOfComparisons": -1,
            "clusteringOptions": {"enabled": True, "algorithm": "AGGLOMERATIVE"},
            "debugParser": False, "normalize": False, "analyzeComments": False,
        }
        zf.writestr("options.json", json.dumps(options))

        # runInformation: real total-comparisons count, honest zero/empty for the stats we don't track (execution time, failures)
        run_info = {
            "version": {"major": 6, "minor": 3, "patch": 0}, "failedSubmissions": [],
            "dateOfExecution": datetime.date.today().strftime("%d/%m/%y"),
            "executionTime": 0, "totalComparisons": int(len(iu)),
        }
        zf.writestr("runInformation.json", json.dumps(run_info))

        # comparisons: one file per unordered pair, named id1-id2.json like real JPlag (not index-based), since the viewer looks up comparisons by submission id pair; matches come from the real GST tile spans pipeline.py cached, falling back to [] for pairs GST found no tile in (below min_match_length, not a real gap in coverage)
        for a, b in zip(iu.tolist(), ju.tolist()):
            score = float(fused_matrix[a, b])
            matches = gst_matches.get((ids[a], ids[b])) or gst_matches.get((ids[b], ids[a])) or []
            comp = {
                "firstSubmissionId": ids[a], "secondSubmissionId": ids[b],
                "similarities": {"AVG": score, "MAX": score},
                "matches": matches,
                "firstSimilarity": score, "secondSimilarity": score,
            }
            zf.writestr(f"comparisons/{ids[a]}-{ids[b]}.json", json.dumps(comp))

        # topComparisons: the highest-scoring pairs overall, same shape as JPlag's own summary list
        order = np.argsort(-fused_matrix[iu, ju])[:min(100, len(iu))]
        top_comparisons = [
            {"firstSubmission": ids[iu[k]], "secondSubmission": ids[ju[k]],
             "similarities": {"AVG": float(fused_matrix[iu[k], ju[k]]), "MAX": float(fused_matrix[iu[k], ju[k]])}}
            for k in order
        ]
        zf.writestr("topComparisons.json", json.dumps(top_comparisons))

        # files + submissionFileIndex: copy every submission's real source into files/<id>/... so the viewer can display it even without match highlighting
        file_index = copy_submission_files(zf, submission_paths)
        zf.writestr("submissionFileIndex.json", json.dumps({"fileIndexes": file_index}))


def generate_report(root_dirs: list[str], output_dir: str, fusion_method: str = 'snf', cluster_method: str = 'hdbscan', auto_tune: bool = True) -> str:
    # running: blind mode -- no dataset/labels-csv argument exists anywhere in this module, so there's no ground-truth path to take even by accident
    results_dir = Path(output_dir)
    results_dir.mkdir(parents=True, exist_ok=True)
    hdbscan_clusters, leiden_clusters, agglomerative_clusters = run_pipeline(
        root_dirs, fusion_method=fusion_method, output_dir=output_dir, auto_tune=auto_tune,
    )
    clusters_by_method = {"hdbscan": hdbscan_clusters, "leiden": leiden_clusters, "agglomerative": agglomerative_clusters}

    # loading: reload the ordered paths and fused matrix run_pipeline just wrote to results_dir, same pattern main.py uses
    with open(results_dir / "paths.json") as f:
        submission_paths = json.load(f)
    fused_matrix = np.load(results_dir / "S_fused.npy")

    # loading matches: pipeline.py already computed and cached these alongside gst_coverage.npy, so reuse them instead of re-running GST
    gst_matches = load_gst_matches(GST_CACHE_DIR / "gst_matches.json")

    # packaging: write the JPlag archive from the fused matrix + chosen method's cluster assignments + real GST match spans
    archive_path = str(results_dir / "archive.jplag")
    build_jplag_archive(archive_path, submission_paths, fused_matrix, clusters_by_method[cluster_method], root_dirs, gst_matches=gst_matches)

    return archive_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the pipeline over a blind dataset (no ground truth) and produce archive.jplag")
    parser.add_argument("root_dirs", nargs='+', help="One or more root directories containing submissions")
    parser.add_argument("--output-dir", required=True, help="Where to write paths.json/S_fused.npy/clusters_*.json/archive.jplag")
    parser.add_argument("--fusion-method", choices=['snf', 'noisy_or'], default='snf')
    parser.add_argument("--cluster-method", choices=['hdbscan', 'leiden', 'agglomerative'], default='hdbscan', help="Which clustering to bake into archive.jplag's cluster.json")
    parser.add_argument("--no-auto-tune", dest="auto_tune", action="store_false", help="Use fixed clustering hyperparameters instead of DBCV auto-tuning (auto-tune is on by default here since there's no ground truth to hand-tune against)")
    args = parser.parse_args()

    archive_path = generate_report(
        args.root_dirs, args.output_dir, fusion_method=args.fusion_method,
        cluster_method=args.cluster_method, auto_tune=args.auto_tune,
    )
    print(f"Wrote {archive_path}")
