import os
import glob
import shutil
import subprocess
import logging
import networkx as nx

class JoernAutomationParser:
    """Automates Joern CLI commands and collapses structural slices into singular GraphML files."""
    def __init__(self, joern_path=""):
        self.joern_path = joern_path
        self.parse_bin = os.path.join(joern_path, "joern-parse") if joern_path else "joern-parse"
        self.export_bin = os.path.join(joern_path, "joern-export") if joern_path else "joern-export"

    def process_submission_folder(self, source_dir, output_dir):
        """
        Iterates through source code files, generates intermediate CPG binaries,
        and builds single monolithic directed GraphML files per student submission.
        Skips processing if the target GraphML file already exists.
        """
        os.makedirs(output_dir, exist_ok=True)
        
        if not os.path.exists(source_dir):
            logging.error(f"Source directory '{source_dir}' does not exist.")
            return False

        # Scan for student subdirectories or standalone Java code files
        items = [os.path.join(source_dir, x) for x in os.listdir(source_dir)]
        submissions = [x for x in items if os.path.isdir(x) or x.endswith('.java')]

        if not submissions:
            logging.warning(f"No source submissions found in {source_dir}.")
            return False

        logging.info(f"Found {len(submissions)} submission(s) to scan/process via Joern.")

        for path in submissions:
            student_id = os.path.basename(path).replace(".java", "")
            cpg_bin_path = os.path.join(output_dir, f"{student_id}_cpg.bin")
            
            # Temporary folder for Joern's multi-file XML dump
            temp_stage_dir = os.path.join(output_dir, f"{student_id}_tmp_stage")
            # Final output destination: One big standalone file per student
            final_graphml_path = os.path.join(output_dir, f"{student_id}.graphml")

            # --- SMART CACHE SKIP CHECK ---
            if os.path.exists(final_graphml_path):
                logging.info(f"[{student_id}] Found existing GraphML export. Skipping Joern parsing pipeline.")
                continue

            try:
                logging.info(f"[{student_id}] Compiling source code to CPG binary...")
                subprocess.run([self.parse_bin, path, "--output", cpg_bin_path], 
                               check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

                logging.info(f"[{student_id}] Exporting fragmented subgraphs to staging...")
                subprocess.run([
                    self.export_bin, 
                    cpg_bin_path, 
                    "--repr", "cpg", 
                    "--format", "graphml", 
                    "--out", temp_stage_dir
                ], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                
                # --- MULTI-RELATIONAL COMPOSITION STEP ---
                logging.info(f"[{student_id}] Aggregating all XML fragments into single GraphML dataset...")
                xml_files = glob.glob(os.path.join(temp_stage_dir, "**", "export.xml"), recursive=True)
                
                if xml_files:
                    unified_graph = nx.MultiDiGraph()
                    
                    for xml_file in xml_files:
                        try:
                            sub_graph = nx.read_graphml(xml_file)
                            unified_graph = nx.compose(unified_graph, sub_graph)
                        except Exception as slice_err:
                            logging.warning(f"[{student_id}] Skipped parsing component slice {os.path.basename(xml_file)}: {slice_err}")
                    
                    # Write out the single unified GraphML file
                    nx.write_graphml(unified_graph, final_graphml_path)
                    logging.info(f"[{student_id}] Successfully generated: {final_graphml_path}")
                else:
                    logging.warning(f"[{student_id}] No structural components were generated by the exporter.")

                # --- AUTO-CLEANUP STEP ---
                if os.path.exists(cpg_bin_path):
                    os.remove(cpg_bin_path)
                if os.path.exists(temp_stage_dir):
                    shutil.rmtree(temp_stage_dir)

            except subprocess.CalledProcessError as e:
                logging.error(f"Joern failed processing {student_id}. Error details:\n{e.stderr.decode('utf-8', errors='ignore')}")
                if os.path.exists(cpg_bin_path): 
                    os.remove(cpg_bin_path)
                if os.path.exists(temp_stage_dir): 
                    shutil.rmtree(temp_stage_dir)
            except FileNotFoundError:
                logging.error("Joern CLI utilities not detected on system PATH. Please verify your system setup.")
                return False
                
        return True
